// AUTO-GENERATED by scripts/gen-example-registry.mjs — do not edit by hand.
import type { ComponentType } from "react";

import AccordionDefaultOpen from "./accordion-default-open";
import AccordionDemo from "./accordion-demo";
import AccordionMultiple from "./accordion-multiple";
import AlertDemo from "./alert-demo";
import AlertDestructive from "./alert-destructive";
import AlertDialogControlled from "./alert-dialog-controlled";
import AlertDialogDemo from "./alert-dialog-demo";
import AlertDialogWithMedia from "./alert-dialog-with-media";
import AlertTitleOnly from "./alert-title-only";
import AspectRatioClassic from "./aspect-ratio-classic";
import AspectRatioDemo from "./aspect-ratio-demo";
import AspectRatioSquare from "./aspect-ratio-square";
import AvatarDemo from "./avatar-demo";
import AvatarGroup from "./avatar-group";
import AvatarSizes from "./avatar-sizes";
import BadgeDemo from "./badge-demo";
import BadgeVariants from "./badge-variants";
import BreadcrumbCustomSeparator from "./breadcrumb-custom-separator";
import BreadcrumbDemo from "./breadcrumb-demo";
import BreadcrumbWithEllipsis from "./breadcrumb-with-ellipsis";
import ButtonDemo from "./button-demo";
import ButtonDisabled from "./button-disabled";
import ButtonGroupDemo from "./button-group-demo";
import ButtonGroupVertical from "./button-group-vertical";
import ButtonGroupWithInput from "./button-group-with-input";
import ButtonSizes from "./button-sizes";
import ButtonVariants from "./button-variants";
import ButtonWithIcon from "./button-with-icon";
import CalendarDemo from "./calendar-demo";
import CalendarDropdown from "./calendar-dropdown";
import CalendarRange from "./calendar-range";
import CardContentOnly from "./card-content-only";
import CardDemo from "./card-demo";
import CardSmall from "./card-small";
import CarouselDemo from "./carousel-demo";
import CarouselLoop from "./carousel-loop";
import CarouselMultipleSlides from "./carousel-multiple-slides";
import ChartArea from "./chart-area";
import ChartDemo from "./chart-demo";
import ChartLine from "./chart-line";
import CheckboxDemo from "./checkbox-demo";
import CheckboxGroup from "./checkbox-group";
import CheckboxStates from "./checkbox-states";
import CollapsibleDefaultOpen from "./collapsible-default-open";
import CollapsibleDemo from "./collapsible-demo";
import CollapsibleDisabled from "./collapsible-disabled";
import ComboboxDemo from "./combobox-demo";
import ComboboxGrouped from "./combobox-grouped";
import ComboboxMultiselect from "./combobox-multiselect";
import ComboboxWithClear from "./combobox-with-clear";
import CommandDemo from "./command-demo";
import CommandDialog from "./command-dialog";
import ContextMenuCheckbox from "./context-menu-checkbox";
import ContextMenuDemo from "./context-menu-demo";
import ContextMenuSubmenu from "./context-menu-submenu";
import DialogDemo from "./dialog-demo";
import DialogWithCloseButton from "./dialog-with-close-button";
import DirectionDemo from "./direction-demo";
import DirectionRtl from "./direction-rtl";
import DrawerDemo from "./drawer-demo";
import DrawerRight from "./drawer-right";
import DropdownMenuCheckbox from "./dropdown-menu-checkbox";
import DropdownMenuDemo from "./dropdown-menu-demo";
import DropdownMenuRadio from "./dropdown-menu-radio";
import DropdownMenuWithIcons from "./dropdown-menu-with-icons";
import EmptyDemo from "./empty-demo";
import EmptyMinimal from "./empty-minimal";
import EmptyNoResults from "./empty-no-results";
import FieldDemo from "./field-demo";
import FieldFieldset from "./field-fieldset";
import FieldHorizontal from "./field-horizontal";
import FieldWithError from "./field-with-error";
import HoverCardDemo from "./hover-card-demo";
import HoverCardOpenByDefault from "./hover-card-open-by-default";
import HoverCardTopPlacement from "./hover-card-top-placement";
import InputDemo from "./input-demo";
import InputDisabled from "./input-disabled";
import InputGroupDemo from "./input-group-demo";
import InputGroupInvalid from "./input-group-invalid";
import InputGroupTextAddon from "./input-group-text-addon";
import InputGroupWithButton from "./input-group-with-button";
import InputInvalid from "./input-invalid";
import InputOtpDemo from "./input-otp-demo";
import InputOtpDisabled from "./input-otp-disabled";
import InputOtpFourDigit from "./input-otp-four-digit";
import InputOtpWithSeparator from "./input-otp-with-separator";
import InputTypes from "./input-types";
import ItemDemo from "./item-demo";
import ItemGroup from "./item-group";
import ItemVariants from "./item-variants";
import ItemWithHeaderFooter from "./item-with-header-footer";
import KbdCombos from "./kbd-combos";
import KbdDemo from "./kbd-demo";
import KbdSingleKey from "./kbd-single-key";
import LabelDemo from "./label-demo";
import LabelDisabled from "./label-disabled";
import LabelWithCheckbox from "./label-with-checkbox";
import MenubarCheckboxRadio from "./menubar-checkbox-radio";
import MenubarDemo from "./menubar-demo";
import MenubarSubmenu from "./menubar-submenu";
import NativeSelectDemo from "./native-select-demo";
import NativeSelectOptGroups from "./native-select-opt-groups";
import NativeSelectSizes from "./native-select-sizes";
import NativeSelectStates from "./native-select-states";
import NavigationMenuDemo from "./navigation-menu-demo";
import NavigationMenuLinksOnly from "./navigation-menu-links-only";
import NavigationMenuMultiple from "./navigation-menu-multiple";
import PaginationControlled from "./pagination-controlled";
import PaginationDemo from "./pagination-demo";
import PaginationWithEllipsis from "./pagination-with-ellipsis";
import PopoverDemo from "./popover-demo";
import PopoverOpenDefault from "./popover-open-default";
import PopoverWithForm from "./popover-with-form";
import ProgressComplete from "./progress-complete";
import ProgressDemo from "./progress-demo";
import ProgressWithLabel from "./progress-with-label";
import RadioGroupDemo from "./radio-group-demo";
import RadioGroupDisabled from "./radio-group-disabled";
import ResizableDemo from "./resizable-demo";
import ResizableThreeColumns from "./resizable-three-columns";
import ResizableVertical from "./resizable-vertical";
import ScrollAreaDemo from "./scroll-area-demo";
import ScrollAreaHorizontal from "./scroll-area-horizontal";
import SelectDemo from "./select-demo";
import SelectGrouped from "./select-grouped";
import SelectSmall from "./select-small";
import SeparatorDemo from "./separator-demo";
import SeparatorVertical from "./separator-vertical";
import SheetBottom from "./sheet-bottom";
import SheetDemo from "./sheet-demo";
import SheetLeft from "./sheet-left";
import SidebarDemo from "./sidebar-demo";
import SidebarIconCollapsible from "./sidebar-icon-collapsible";
import SkeletonCard from "./skeleton-card";
import SkeletonDemo from "./skeleton-demo";
import SliderDemo from "./slider-demo";
import SliderDisabled from "./slider-disabled";
import SliderRange from "./slider-range";
import SliderStepped from "./slider-stepped";
import SonnerDemo from "./sonner-demo";
import SonnerError from "./sonner-error";
import SonnerSuccess from "./sonner-success";
import SonnerWithAction from "./sonner-with-action";
import SpinnerDemo from "./spinner-demo";
import SpinnerInsideButton from "./spinner-inside-button";
import SpinnerLarge from "./spinner-large";
import SwitchDemo from "./switch-demo";
import SwitchDisabled from "./switch-disabled";
import SwitchSizes from "./switch-sizes";
import SwitchWithLabel from "./switch-with-label";
import TableDemo from "./table-demo";
import TableWithFooter from "./table-with-footer";
import TabsDemo from "./tabs-demo";
import TabsLine from "./tabs-line";
import TabsVertical from "./tabs-vertical";
import TextareaDemo from "./textarea-demo";
import TextareaDisabled from "./textarea-disabled";
import TextareaInvalid from "./textarea-invalid";
import ToggleDemo from "./toggle-demo";
import ToggleDisabled from "./toggle-disabled";
import ToggleGroupDemo from "./toggle-group-demo";
import ToggleGroupJoined from "./toggle-group-joined";
import ToggleGroupMultiSelect from "./toggle-group-multi-select";
import ToggleGroupVertical from "./toggle-group-vertical";
import ToggleSizes from "./toggle-sizes";
import ToggleVariants from "./toggle-variants";
import TooltipDemo from "./tooltip-demo";
import TooltipIconButton from "./tooltip-icon-button";
import TooltipPlacement from "./tooltip-placement";

export const exampleRegistry: Record<string, ComponentType> = {
  "accordion-default-open": AccordionDefaultOpen,
  "accordion-demo": AccordionDemo,
  "accordion-multiple": AccordionMultiple,
  "alert-demo": AlertDemo,
  "alert-destructive": AlertDestructive,
  "alert-dialog-controlled": AlertDialogControlled,
  "alert-dialog-demo": AlertDialogDemo,
  "alert-dialog-with-media": AlertDialogWithMedia,
  "alert-title-only": AlertTitleOnly,
  "aspect-ratio-classic": AspectRatioClassic,
  "aspect-ratio-demo": AspectRatioDemo,
  "aspect-ratio-square": AspectRatioSquare,
  "avatar-demo": AvatarDemo,
  "avatar-group": AvatarGroup,
  "avatar-sizes": AvatarSizes,
  "badge-demo": BadgeDemo,
  "badge-variants": BadgeVariants,
  "breadcrumb-custom-separator": BreadcrumbCustomSeparator,
  "breadcrumb-demo": BreadcrumbDemo,
  "breadcrumb-with-ellipsis": BreadcrumbWithEllipsis,
  "button-demo": ButtonDemo,
  "button-disabled": ButtonDisabled,
  "button-group-demo": ButtonGroupDemo,
  "button-group-vertical": ButtonGroupVertical,
  "button-group-with-input": ButtonGroupWithInput,
  "button-sizes": ButtonSizes,
  "button-variants": ButtonVariants,
  "button-with-icon": ButtonWithIcon,
  "calendar-demo": CalendarDemo,
  "calendar-dropdown": CalendarDropdown,
  "calendar-range": CalendarRange,
  "card-content-only": CardContentOnly,
  "card-demo": CardDemo,
  "card-small": CardSmall,
  "carousel-demo": CarouselDemo,
  "carousel-loop": CarouselLoop,
  "carousel-multiple-slides": CarouselMultipleSlides,
  "chart-area": ChartArea,
  "chart-demo": ChartDemo,
  "chart-line": ChartLine,
  "checkbox-demo": CheckboxDemo,
  "checkbox-group": CheckboxGroup,
  "checkbox-states": CheckboxStates,
  "collapsible-default-open": CollapsibleDefaultOpen,
  "collapsible-demo": CollapsibleDemo,
  "collapsible-disabled": CollapsibleDisabled,
  "combobox-demo": ComboboxDemo,
  "combobox-grouped": ComboboxGrouped,
  "combobox-multiselect": ComboboxMultiselect,
  "combobox-with-clear": ComboboxWithClear,
  "command-demo": CommandDemo,
  "command-dialog": CommandDialog,
  "context-menu-checkbox": ContextMenuCheckbox,
  "context-menu-demo": ContextMenuDemo,
  "context-menu-submenu": ContextMenuSubmenu,
  "dialog-demo": DialogDemo,
  "dialog-with-close-button": DialogWithCloseButton,
  "direction-demo": DirectionDemo,
  "direction-rtl": DirectionRtl,
  "drawer-demo": DrawerDemo,
  "drawer-right": DrawerRight,
  "dropdown-menu-checkbox": DropdownMenuCheckbox,
  "dropdown-menu-demo": DropdownMenuDemo,
  "dropdown-menu-radio": DropdownMenuRadio,
  "dropdown-menu-with-icons": DropdownMenuWithIcons,
  "empty-demo": EmptyDemo,
  "empty-minimal": EmptyMinimal,
  "empty-no-results": EmptyNoResults,
  "field-demo": FieldDemo,
  "field-fieldset": FieldFieldset,
  "field-horizontal": FieldHorizontal,
  "field-with-error": FieldWithError,
  "hover-card-demo": HoverCardDemo,
  "hover-card-open-by-default": HoverCardOpenByDefault,
  "hover-card-top-placement": HoverCardTopPlacement,
  "input-demo": InputDemo,
  "input-disabled": InputDisabled,
  "input-group-demo": InputGroupDemo,
  "input-group-invalid": InputGroupInvalid,
  "input-group-text-addon": InputGroupTextAddon,
  "input-group-with-button": InputGroupWithButton,
  "input-invalid": InputInvalid,
  "input-otp-demo": InputOtpDemo,
  "input-otp-disabled": InputOtpDisabled,
  "input-otp-four-digit": InputOtpFourDigit,
  "input-otp-with-separator": InputOtpWithSeparator,
  "input-types": InputTypes,
  "item-demo": ItemDemo,
  "item-group": ItemGroup,
  "item-variants": ItemVariants,
  "item-with-header-footer": ItemWithHeaderFooter,
  "kbd-combos": KbdCombos,
  "kbd-demo": KbdDemo,
  "kbd-single-key": KbdSingleKey,
  "label-demo": LabelDemo,
  "label-disabled": LabelDisabled,
  "label-with-checkbox": LabelWithCheckbox,
  "menubar-checkbox-radio": MenubarCheckboxRadio,
  "menubar-demo": MenubarDemo,
  "menubar-submenu": MenubarSubmenu,
  "native-select-demo": NativeSelectDemo,
  "native-select-opt-groups": NativeSelectOptGroups,
  "native-select-sizes": NativeSelectSizes,
  "native-select-states": NativeSelectStates,
  "navigation-menu-demo": NavigationMenuDemo,
  "navigation-menu-links-only": NavigationMenuLinksOnly,
  "navigation-menu-multiple": NavigationMenuMultiple,
  "pagination-controlled": PaginationControlled,
  "pagination-demo": PaginationDemo,
  "pagination-with-ellipsis": PaginationWithEllipsis,
  "popover-demo": PopoverDemo,
  "popover-open-default": PopoverOpenDefault,
  "popover-with-form": PopoverWithForm,
  "progress-complete": ProgressComplete,
  "progress-demo": ProgressDemo,
  "progress-with-label": ProgressWithLabel,
  "radio-group-demo": RadioGroupDemo,
  "radio-group-disabled": RadioGroupDisabled,
  "resizable-demo": ResizableDemo,
  "resizable-three-columns": ResizableThreeColumns,
  "resizable-vertical": ResizableVertical,
  "scroll-area-demo": ScrollAreaDemo,
  "scroll-area-horizontal": ScrollAreaHorizontal,
  "select-demo": SelectDemo,
  "select-grouped": SelectGrouped,
  "select-small": SelectSmall,
  "separator-demo": SeparatorDemo,
  "separator-vertical": SeparatorVertical,
  "sheet-bottom": SheetBottom,
  "sheet-demo": SheetDemo,
  "sheet-left": SheetLeft,
  "sidebar-demo": SidebarDemo,
  "sidebar-icon-collapsible": SidebarIconCollapsible,
  "skeleton-card": SkeletonCard,
  "skeleton-demo": SkeletonDemo,
  "slider-demo": SliderDemo,
  "slider-disabled": SliderDisabled,
  "slider-range": SliderRange,
  "slider-stepped": SliderStepped,
  "sonner-demo": SonnerDemo,
  "sonner-error": SonnerError,
  "sonner-success": SonnerSuccess,
  "sonner-with-action": SonnerWithAction,
  "spinner-demo": SpinnerDemo,
  "spinner-inside-button": SpinnerInsideButton,
  "spinner-large": SpinnerLarge,
  "switch-demo": SwitchDemo,
  "switch-disabled": SwitchDisabled,
  "switch-sizes": SwitchSizes,
  "switch-with-label": SwitchWithLabel,
  "table-demo": TableDemo,
  "table-with-footer": TableWithFooter,
  "tabs-demo": TabsDemo,
  "tabs-line": TabsLine,
  "tabs-vertical": TabsVertical,
  "textarea-demo": TextareaDemo,
  "textarea-disabled": TextareaDisabled,
  "textarea-invalid": TextareaInvalid,
  "toggle-demo": ToggleDemo,
  "toggle-disabled": ToggleDisabled,
  "toggle-group-demo": ToggleGroupDemo,
  "toggle-group-joined": ToggleGroupJoined,
  "toggle-group-multi-select": ToggleGroupMultiSelect,
  "toggle-group-vertical": ToggleGroupVertical,
  "toggle-sizes": ToggleSizes,
  "toggle-variants": ToggleVariants,
  "tooltip-demo": TooltipDemo,
  "tooltip-icon-button": TooltipIconButton,
  "tooltip-placement": TooltipPlacement,
};

export type ExampleName = keyof typeof exampleRegistry;
